### ISSUE TITLE
need help with "hd0_12m.img"

### ISSUE THREAD

**Issue by hathach** [moononournation/T-Deck#1]
Hi, first thank you for your x86 work on esp32-s3. I am trying to build and test out with `esp32-faux86/esp32-faux86.ino` examples. Got it compiled and upload successfully but I got an error from Serial.

```
[StdioDiskInterface] Error loading file /ffat/hd0_12m.img
```

Look like I am missing hd0_12m.img on the fat partition, though I have try to search but couldn't find where is `hd0_12m.img`. Did I miss something obvious, if possible could you provide information on how to generate the file, or maybe upload the file into the example folder to make it eaiser for me and others to build. Thank you
 
https://github.com/moononournation/T-Deck/blob/8aa23d71571b51c54a57e07dc2a80915f65f83c0/esp32-faux86/esp32-faux86.ino#L204C47-L204C66

**Comment by moononournation** [comment]
https://www.instructables.com/T-Deck/

**Comment by hathach** [comment]
ah, thank you very much for super fast response, seem like it will take some effort to make one :)

**Comment by hathach** [comment]
following instruction in video in the above link, I am able to create an hd0_12m.img with windows 3.0. Thank you very much for detailed tutorial.
