### ISSUE TITLE
esp32-faux86 is slower then it should, reversed video, keyboard not working

### ISSUE THREAD

**Issue by SvenMb** [moononournation/T-Deck#2]
I compiled und uploaded the esp32-faux86 example to my T-Deck, but I had some issues with it:

- I tried to compile on platformIO and Arduino and both resulted in a much slower emulation speed, then on your video, also the BIOS and DOS output was on white screen and not black screen like you showed. What can be the source of this strange behaviour?
- keyboard can not be used, I get the message "LILYGO Keyboard not online!"

I used the T-Deck before with meshtastic firmware and there where no issues.

thanks

**Comment by moononournation** [comment]
Only support Arduino IDE

**Comment by SvenMb** [comment]
I tried both, Arduino and platformIO (with arduino plugin), both produced the same result.

Maybe some specific versions? I used the old arduino ide 1.8.19

**Comment by SvenMb** [comment]
Now I tried with current Arduino IDE 2.2.1 and got the same. Attached a photo from BIOS output...

![IMG_20231219_164830](https://github.com/moononournation/T-Deck/assets/36633782/74626e42-01fc-487b-8680-694ee4215a6a)

**Comment by moononournation** [comment]
for the display color inverted, set the st7789 ips parameter to true.
for the keyboard, you may need to upload the custom keyboard program for better response.

**Comment by SvenMb** [comment]
Perfect, all working now and is fast as it should.

Thanks.

**Comment by coolcoder613eb** [comment]
How do I upload the custom keyboard program?
Also, where do I put the disk image so it gets read?

**Comment by SvenMb** [comment]
See  https://github.com/rgrizzell/lilygo-t-deck-keyboard


You could alternatively set TDECK_I2C_FREQ back to the original number 100000U, then it works without new keyboard firmware.
