### ISSUE TITLE
Not loading game from SD Card NES emulation on T-Deck

### ISSUE THREAD

**Issue by sombrie** [moononournation/T-Deck#3]
Firstly, thank you so very much for your amazing work and contributions. I found you on Instructables and built out an emulator based on the T-8 v1.17 and it worked amazingly!!
 I have been checking your repositories here at github periodically and I was excited to see your latest repo for the S3 T-Deck!! LilyGo has done a fantastic job with this device and I am quite pleased. 
That said I have attempted to run the NES example you provided and I am just stuck. 
With the SD card inserted I get the Nofrendo splash screen, but then nothing. Sound is being output but its just a repeating beeping.
When I check the serial console for errors it tells me this:

/fs/zelda.nes
NoFrendo start!
LILYGO Keyboad not online!
key:  255
addr: 0x3FCA994C, size: 61440, line 86 of C:\Users\Abulafia\Documents\Arduino\libraries\arduino-nofrendo-master\src\bitmap.c -- block corrupt

I have looked over this line of code and I am just not familiar enough to correct the issue, I honestly don't really know what this error means. this is the line of code from the aforementioned error:
Line 86 of \src\bitmap.c:
 addr = NOFRENDO_MALLOC(((pitch * height) + 3) & 0xFFFFFFF8); /* add max 32-bit aligned adjustment */
   if (NULL == addr)
      return NULL;
Whats more is I cannot seem to get mkfatfs to work inside of Arduino. So I cannot upload to FFAT partitions. I can use spiffs, and I can probably use littlefs though I'm not sure how to include littlefs in the hw_config.h. 
I created a new partition table for the T-deck and have tested spiffs.
So I came here to see if you have any ideas why I cannot get a game to load from SD card to the T-deck, nor what the "corrupt block" error is. Any thoughts or pointers would be appreciated very much and I send my best wishes.

**Comment by moononournation** [comment]
not tried SD card, i am using flash storage only.
