### ISSUE TITLE
miniz.h error

### ISSUE THREAD

**Issue by nylar357** [moononournation/T-Deck#4]
Before installing its the same error except for miniz.h

After installing miniz library

In file included from c:\Users\c0n7r\Documents\Arduino\libraries\arduinoVNC\src/VNC.h:44:0,
                 from C:\Users\c0n7r\Documents\Arduino\T-Deck-main\ArduinoVNC_VGA\VNC_GFX.h:5,
                 from C:\Users\c0n7r\Documents\Arduino\T-Deck-main\ArduinoVNC_VGA\ArduinoVNC_VGA.ino:65:
c:\Users\c0n7r\Documents\Arduino\libraries\miniz-master/miniz.h:115:10: fatal error: miniz_export.h: No such file or directory
 #include "miniz_export.h"

**Comment by moononournation** [comment]
T-Deck did not require external miniz library
