### ISSUE TITLE
LvglLoRaMessenger: Start Radio failed, code:-707

### ISSUE THREAD

**Issue by civicbynature** [moononournation/T-Deck#5]
Hi thank you for your great examples. 

The LoRaMessenger Code Always fails to start Radio.
I have tested liligo's unitTest code and it has no issue. 
but when I upload your LoRamessenger it gets the error below everytime. 
any ideas what is causing it.  

Output:
Arduino LoRa Messenger
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x15 (USB_UART_CHIP_RESET),boot:0x8 (SPI_FAST_FLASH_BOOT)
Saved PC:0x4209f1be
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x44c
load:0x403c9700,len:0xbe4
load:0x403cc700,len:0x2a38
entry 0x403c98d4
Arduino LoRa Messenger
Init LILYGO Keyboard
Setup done
Start Radio failed,code:-707
Radio not online!
Radio not online!
Radio not online!
Radio not online!

**Comment by moononournation** [comment]
Please get update, it should be ok now.

**Comment by civicbynature** [comment]
thanks for your update. 
the error has now changed to Code: -2 

output:
ESP-ROM:esp32s3-20210327
Arduino LoRa Messenger
Init LILYGO Keyboard
Setup done
Start Radio failed,code:-2
Radio not online!
Radio not online!
Radio not online!

**Comment by civicbynature** [comment]
Solved it! Using your original code: 
in Lora.h Ln 31

added the below.  


bool setupRadio()
{
  // Add mutex to allow multitasking access
  xSemaphore = xSemaphoreCreateBinary();
  assert(xSemaphore);
  xSemaphoreGive(xSemaphore);

  **digitalWrite(TDECK_SDCARD_CS, HIGH);  //testing Nds 
  digitalWrite(TDECK_RADIO_CS, HIGH);
  digitalWrite(TDECK_TFT_CS, HIGH);
  SPI.end();
  SPI.begin(TDECK_SPI_SCK, TDECK_SPI_MISO, TDECK_SPI_MOSI); //SD**


  int state = radio.begin(RADIO_FREQ);
  if (state == RADIOLIB_ERR_NONE)
  {
    Serial.println("Start Radio success!");
  }
  else
  {
    Serial.print("Start Radio failed,code:");
    Serial.println(state);
    Serial.println("lora.h Ln 49 Fail Code");
    return false;
  }
